apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: registry
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      run: registry
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: registry
    spec:
      containers:
      - image: registry
        name: registry
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: registry
  name: registry
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 32030
  selector:
    run: registry
  sessionAffinity: None
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: date-printer
  name: date-printer
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: date-printer
  template:
    metadata:
      labels:
        run: date-printer
    spec:
      containers:
      - image: localhost:32030/date-printer:0.1
        imagePullPolicy: IfNotPresent
        name: date-printer
